DemoScheduler/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^calenders/', include('calenders.urls')),
]

calenders/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'calenders'
urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^available-slots/$', views.available_slots, name='available_slots'),
    url(r'^available-slots/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', views.available_slots, name='available_slots'),
    url(r'^google_calender/$', views.google_calender_permission, name='google_calender_permission'),
	url(r'^attach_calender/$', views.google_auth_return, name='google_auth_return'),
        
]

calenders/models.py
from django.db import models
from django.contrib.auth.models import User


class AppointmentSlot(models.Model):
	'''database table to store sales reps appointment slots'''
	class Meta:
		db_table = "appointment_slots"

	user = models.ForeignKey(User,
							 related_name='slots')
	date = models.DateField()
	start_time = models.TimeField()
	end_time = models.TimeField()
	soft_deleted = models.BooleanField(default=False)


class DemoAppointment(models.Model):
	'''db table to store demo requests by clients,
	   only considering email id as representation of client 
	   for now'''
	class Meta:
		db_table = "appointments"

	user = models.ForeignKey(User,
							 related_name='appointments',
							 null=True, default=None)
	date = models.DateField()
	start_time = models.TimeField()
	client_email = models.EmailField(
        verbose_name='email address',
        max_length=255,
    )
	scheduled = models.BooleanField(default=False)
	soft_deleted = models.BooleanField(default=False)


class UserCalender(models.Model):
	calender_id = models.CharField(max_length=255)
	user = models.ForeignKey(User, related_name='caleder')
	refresh_token = models.CharField(max_length=255)

calenders/forms.py
from django import forms
from django.utils.dateparse import parse_date
import datetime
import time
from .models import AppointmentSlot, DemoAppointment, UserCalender
from .services import get_available_slots_by_date, get_next_sales_rep,\
    schedule_g_calendar_event


class NotValidatedMultipleChoiceFiled(forms.TypedMultipleChoiceField):
    """Field that do not validate if the field values are in self.choices"""

    def to_python(self, value):
        """Override checking method"""
        return map(self.coerce, value)

    def validate(self, value):
        """Nothing to do here"""
        pass


class AppointmentSlotsForm(forms.Form):
    date = NotValidatedMultipleChoiceFiled()
    start_end_time = NotValidatedMultipleChoiceFiled()

    def clean_date(self):
        dates = []
        for date_str in self.cleaned_data['date']:
            dates.append(datetime.datetime.\
                strptime(date_str, '%Y-%m-%d').date())
        return dates

    def clean_start_end_time(self):
        start_end_times = []
        for start_end in self.cleaned_data['start_end_time']:
            start, end = start_end.split('-')
            start, end = datetime.time(*list(map(int,start.split(':')))),\
                         datetime.time(*list(map(int,end.split(':'))))
            start_end_times.append((start,end))
        return start_end_times

    def save(self, user):
        for date in self.cleaned_data['date']:
            for time_slot in self.cleaned_data['start_end_time']:
                slot = AppointmentSlot()
                slot.date = date
                slot.start_time = time_slot[0]
                slot.end_time = time_slot[1]
                slot.user = user
                slot.save()


class DemoScheduleForm(forms.Form):
    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        date = datetime.date(kwargs.pop('year'),
                             kwargs.pop('month'),
                             kwargs.pop('day'))
        super(DemoScheduleForm, self).__init__(*args, **kwargs)
        self._date = date
        avail_slots = get_available_slots_by_date(date)
        self.fields['demo_slot'] = \
            forms.\
            ChoiceField(choices=list(map(lambda time: (time,str(time)), 
                                         avail_slots)))


    def save(self):
        appointment = DemoAppointment()
        appointment.date = self._date
        appointment.start_time = datetime.\
            time(*list(map(int,self.cleaned_data['demo_slot'].split(':'))))
        appointment.client_email = self.cleaned_data['email']
        appointment.scheduled = False
        appointment.soft_deleted = False
        appointment.user = get_next_sales_rep(appointment.date, 
                                              appointment.start_time)
        appointment.save()
        schedule_g_calendar_event(appointment)


class CalendarAttachForm(forms.Form):
    calender_id = forms.CharField()
    refresh_token = forms.CharField()

    def save(self, user):
        calender = UserCalender()
        calender.user = user
        calender.calender_id = self.cleaned_data['calender_id']
        calender.refresh_token = self.cleaned_data['refresh_token']
        calender.save()

calenders/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST
from .forms import AppointmentSlotsForm, DemoScheduleForm, CalendarAttachForm
from .services import get_existing_demos
from oauth2client.contrib import xsrfutil
import httplib2
from oauth2client.client import OAuth2WebServerFlow
from googleapiclient.discovery import build
from django.conf import settings
import datetime


FLOW=OAuth2WebServerFlow(
		client_id=settings.G_CLIENT_ID,
		client_secret=settings.G_CLIENT_SECRET,
		scope=['https://www.googleapis.com/auth/calendar'],
		redirect_uri=settings.G_REDIRECT_URI
		)


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('calenders:index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def index(request):
	if request.method == 'POST':
	    form = AppointmentSlotsForm(request.POST)
	    if form.is_valid():
	        form.save(request.user)
	else:
		form = AppointmentSlotsForm()
	calendar_attached = False
	if request.user.caleder.first() != None:
		calendar_attached = True
	return render(request, 'calenders/landing.html',
				  {'form':form, 'attach_calender':calendar_attached})


def available_slots(request, year=None, month=None, day=None):
	if year == None or month == None or day == None:
		return render(request, 'calenders/schedule_demo.html')
	if request.method == 'GET':
		form = DemoScheduleForm(year=int(year),
								month=int(month),
								day=int(day))
		return render(request,
					  'calenders/schedule_demo.html',
					  {'form':form, 
					   'demos':get_existing_demos(int(year),
					   						      int(month),
					   						      int(day))})
	if request.method == 'POST':
		form = DemoScheduleForm(request.POST,
								year=int(year),
								month=int(month),
								day=int(day))
		if form.is_valid():
			form.save()
			return render(request, 
						  'calenders/schedule_demo.html',
						  {'form':form})
	return render(request, 'calenders/schedule_demo.html')


def google_calender_permission(request):
	FLOW.params['state'] = xsrfutil.generate_token(settings.SECRET_KEY,
												   request.user)
	FLOW.params['access_type'] = 'offline' 
	authorize_url = FLOW.step1_get_authorize_url()
	return HttpResponseRedirect(authorize_url)


def google_auth_return(request):
	if not xsrfutil.validate_token(settings.SECRET_KEY,
								   request.GET.get('state').encode("utf-8"),
								   request.user):
		return  HttpResponseBadRequest()
	credential = FLOW.step2_exchange(request.GET)
	print(credential.to_json())
	http = httplib2.Http()
	http = credential.authorize(http)
	service = build("calendar", "v3", http=http)
	calendar_data = service.calendarList().list().execute()
	for calendar in calendar_data['items']:
		if 'primary' in calendar and calendar['primary'] == True:
			form = CalendarAttachForm({
				'calender_id':calendar['id'],
				'refresh_token':credential.refresh_token})
			if form.is_valid():
				form.save(request.user)
	return redirect('calenders:index')

calenders/templates/calenders/landing.html
<!DOCTYPE html>
<html>
<head>
	<title>Welcome to Calender.</title>
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!--Import materialize.css-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
	<!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
</head>
<body>
	
	{% if not attach_calender %}
		<a href="/calenders/google_calender/">Attach Google calender</a>
	{% else %}
	<form method="post">
		{% csrf_token %}
		<div class="datesDiv">
			<input name='date' type="date" />
		</div>
		<button id="addDateButton" name="addDateButton" type="button">Add Date</button>
		<div class="slotsDiv">
			<div class="timeSlot">
				<input name="start_time" type="time" class="startTime" />
				<input name="end_time" type="time" class="endTime" />
				<input name="start_end_time" class="timeSlotComposite" type="text" value="00:00:00-00:00:00" hidden>
			</div>
		</div>
		<button id="addSlotButton" name="addSlotButton" type="button">Add Slot</button>
		<br/>
		<br/><br/><br/><br/><br/>
		<input type="submit" value="Add Availability"/>
	</form>
	<br/><br/>
	<a href="{% url 'calenders:logout'%}">Logout</a>
	{% endif %}
</body>
<script type="text/javascript">
	$(document).ready(function(){
		//button function to add multiple dates.
		$('#addDateButton').on('click', function(){
			$('.datesDiv').append('<input name="date" type="date" />');
		});
		$('#addSlotButton').on('click', function(){
			$('.slotsDiv').append('<div class="timeSlot"><input name="start_time" type="time" class="startTime" /><input name="end_time" type="time" class="endTime" /><input name="start_end_time" class="timeSlotComposite" type="text" value="00:00:00-00:00:00" hidden></div>');
		});
		$('.slotsDiv').on('change','div.timeSlot > input.startTime', function(event){
			start = $(event.target).val();
			composite_hidden_input = $($(event.target).parent('div.timeSlot').children('input.timeSlotComposite')[0]);
			end = composite_hidden_input.val().split('-')[1];
			composite_hidden_input.val(start + '-' + end);
		});
		$('.slotsDiv').on('change','div.timeSlot > input.endTime', function(event){
			end = $(event.target).val();
			composite_hidden_input = $($(event.target).parent('div.timeSlot').children('input.timeSlotComposite')[0]);
			start = composite_hidden_input.val().split('-')[0];
			composite_hidden_input.val(start + '-' + end);
		});
	});
</script>
<style type="text/css">
	body{
		margin:5%;
	}
</style>
</html>

calenders/templates/calenders/schedule_demo.html
<!DOCTYPE html>
<html>
<head>
	<title>Schedule a demo</title>
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!--Import materialize.css-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
	<!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
</head>
<body>
	<div class="datesDiv">
			<input id="appointmentDate" name='date' type="date" />
	</div>
	{% if form %}
		<form method="post">
			{% csrf_token %}
			{{ form }}
			<button type="submit">Schedule Demo</button>
		</form>
	{% endif %}
	<br/><br/>
	{% if demos %}
		<p>Demos Scheduled on the day</p>
		<table>
	  		<tr>
	    		<th>Sales Rep</th>
	    		<th>Time</th>
	    		<th>Demo Client</th>
	  		</tr>
		{% for demo in demos %}
			<tr>
		    	<td>{{demo.user.username}}</td>
		    	<td>{{demo.start_time}}</td>
		    	<td>{{demo.client_email}}</td>
		  	</tr>
		{% endfor %}
		</table>
	{% endif %}
</body>
<script type="text/javascript">
	$(document).ready(function(){
		//button function to add multiple dates.
		$('#appointmentDate').on('change', function(){
			window.location.href = $('#appointmentDate').val().replace(/-/g,'/');
		});
	});
</script>
<style type="text/css">
	select {
		display: block !important;
	}
	table {
    	font-family: arial, sans-serif;
    	border-collapse: collapse;
    	width: 100%;
	}
	td, th {
	    border: 1px solid #dddddd;
	    text-align: left;
	    padding: 8px;
	}
	tr:nth-child(even) {
	    background-color: #dddddd;
	}
	body{
		margin:5%;
	}
</style>
</style>
</html>